# Generated by Django 5.2.13 on 2026-05-01 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_status', models.CharField(choices=[('active', 'active'), ('finished', 'finished'), ('canceled', 'canceled')], default='active', max_length=10)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.parking')),
            ],
        ),
    ]
