# Generated by Django 5.2.13 on 2026-05-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='period_type',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('monthly', 'Per Month')], default='hourly', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='active', max_length=10),
        ),
    ]
