# Generated by Django 5.2.13 on 2026-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_period_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
