# Generated by Django 5.2.13 on 2026-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parking_type', models.CharField(choices=[('open_lot', 'open lot'), ('garage', 'garage'), ('other', 'other')], default='open_lot', max_length=20)),
                ('distance', models.CharField(choices=[('center', 'In Center'), ('near', 'Up to 500m'), ('far', 'Up to 1km'), ('very_far', 'Over 1km')], default='center', max_length=20)),
            ],
        ),
    ]
