# Generated by Django 5.2.13 on 2026-05-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='adress',
            new_name='address',
        ),
    ]
